apiVersion: v1
kind: Service
metadata:
  name: mci-endpoint
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: website
  ports:
  - name: http
    nodePort: 32100
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort

